from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from app.agents.specs import AgentSpec
from app.policy.engine import PolicyEngine
from app.schemas.common import ActorType, AuditRecord, PermissionLevel
from app.schemas.domain import ApprovalRequest, EventCreate, EventRecord, MemoryRecord, TaskRecord
from app.storage.sqlite import SQLiteStorage
from app.tools.registry import ToolRegistry
from app.utils.redaction import hash_payload

logger = logging.getLogger(__name__)


@dataclass
class OrchestratorContext:
    storage: SQLiteStorage
    policy_engine: PolicyEngine
    tool_registry: ToolRegistry
    agents: dict[str, AgentSpec]


class OrchestratorEngine:
    def __init__(self, context: OrchestratorContext) -> None:
        self.ctx = context
        self._running = False
        self._sleep_seconds = 0.05

    def ingest_event(self, event_in: EventCreate) -> EventRecord:
        event = EventRecord(**event_in.model_dump())
        self.ctx.storage.insert_event(event)
        self._audit(
            trace_id=event.trace_id,
            actor_id="AIo",
            actor_type=ActorType.ORCHESTRATOR,
            level=PermissionLevel.L0_OBSERVE,
            action=f"event_ingested:{event.event_type}",
            status="completed",
            inputs={"event": event.event_type},
            outputs={"event_id": event.event_id},
            evidence_refs=event.evidence_refs,
        )
        return event

    async def run_loop(self) -> None:
        self._running = True
        logger.info("orchestrator_loop_started")
        while self._running:
            processed = await self.run_once()
            if not processed:
                await asyncio.sleep(self._sleep_seconds)

    def stop(self) -> None:
        self._running = False
        logger.info("orchestrator_loop_stopped")

    async def run_once(self) -> bool:
        pending_events = self.ctx.storage.list_events(status="pending")
        if not pending_events:
            return False
        event = pending_events[0]
        await self._handle_event(event)
        return True

    def execute_approved_action(self, approval_id: str) -> dict[str, Any]:
        approval = self.ctx.storage.get_approval(approval_id)
        if approval is None:
            raise ValueError("approval_not_found")
        if approval.status != "approved":
            raise ValueError("approval_not_approved")
        artifact = self.ctx.storage.get_artifact(approval_id)
        if not artifact:
            raise ValueError("approval_artifact_missing")
        event = self.ctx.storage.get_event_by_trace(approval.trace_id)
        task = self.ctx.storage.get_task_by_trace(approval.trace_id)
        if event is None or task is None:
            raise ValueError("approval_context_missing")

        tool_name = approval.requested_action.get("tool_name")
        if not tool_name:
            raise ValueError("approval_missing_tool")
        spec = self.ctx.tool_registry.get(tool_name)
        action_context = self._build_action_context(task, event, spec)
        decision = self.ctx.policy_engine.evaluate(action_context)
        if decision.requires_approval and decision.required_level == PermissionLevel.L4_HIGH_RISK:
            decision.allowed = True
            decision.requires_approval = False
            decision.reasons.append("approved_by_ceo")

        tool_payload = self._build_tool_payload(task, event, {"approved": True}, spec)
        result = self.ctx.tool_registry.execute(
            name=spec.name,
            payload=tool_payload,
            trace_id=approval.trace_id,
            actor_id=task.assigned_to,
            policy_decision=decision,
            audit_callback=self.ctx.storage.add_audit,
        )
        self.ctx.policy_engine.record_success(action_context)
        self.ctx.storage.update_task_status(task.task_id, "completed", {"approved_result": result})
        if event.status != "completed":
            self.ctx.storage.update_event_status(event.event_id, "completed")
        self.ctx.storage.store_memory(
            MemoryRecord(
                trace_id=task.trace_id,
                scope="long_term",
                key=f"approved:{tool_name}",
                value={"artifact_hash": hash_payload(artifact), "result_hash": hash_payload(result)},
            )
        )
        return result

    async def _handle_event(self, event: EventRecord) -> None:
        logger.info("handling_event", extra={"extra": {"trace_id": event.trace_id, "event_type": event.event_type}})
        risk_level, assigned_agent = self._classify_event(event)
        task = TaskRecord(
            trace_id=event.trace_id,
            title=f"Handle {event.event_type}",
            description="Autogenerated task from orchestration loop.",
            assigned_to=assigned_agent,
            permission_level=risk_level,
            external_impact=risk_level in {PermissionLevel.L3_CONDITIONAL_EXECUTE, PermissionLevel.L4_HIGH_RISK},
            metadata={"event_id": event.event_id, "event_type": event.event_type},
        )
        self.ctx.storage.create_task(task)
        self._audit(
            trace_id=event.trace_id,
            actor_id="AIo",
            actor_type=ActorType.ORCHESTRATOR,
            level=risk_level,
            action="task_created",
            status="completed",
            inputs={"event_type": event.event_type},
            outputs={"task_id": task.task_id, "assigned_to": assigned_agent},
            evidence_refs=event.evidence_refs,
        )

        kill_switch_reasons = self._kill_switch_checks(event)
        if kill_switch_reasons:
            self.ctx.storage.update_task_status(task.task_id, "held", {"kill_switch": kill_switch_reasons})
            self.ctx.storage.update_event_status(event.event_id, "held")
            self._audit(
                trace_id=event.trace_id,
                actor_id="AIo",
                actor_type=ActorType.ORCHESTRATOR,
                level=PermissionLevel.L4_HIGH_RISK,
                action="kill_switch_triggered",
                status="requires_approval",
                inputs={"reasons": kill_switch_reasons},
                outputs={"task_id": task.task_id},
                evidence_refs=event.evidence_refs,
            )
            return

        agent_result = self._dispatch_to_agent(task, event)
        await self._execute_agent_plan(task, event, agent_result)

    def _classify_event(self, event: EventRecord) -> tuple[PermissionLevel, str]:
        mapping = {
            "customer_complaint": (PermissionLevel.L1_PROPOSE, "AI2"),
            "invoice_request": (PermissionLevel.L2_INTERNAL_EXECUTE, "AI3"),
            "sales_lead": (PermissionLevel.L2_INTERNAL_EXECUTE, "AI1"),
            "external_outreach": (PermissionLevel.L3_CONDITIONAL_EXECUTE, "AI1"),
            "automation_request": (PermissionLevel.L2_INTERNAL_EXECUTE, "AI4"),
            "money_movement": (PermissionLevel.L4_HIGH_RISK, "AI3"),
            "suspicious_instruction": (PermissionLevel.L4_HIGH_RISK, "AI4"),
        }
        return mapping.get(event.event_type, (PermissionLevel.L1_PROPOSE, "AIo"))

    def _kill_switch_checks(self, event: EventRecord) -> list[str]:
        payload = event.payload
        reasons: list[str] = []
        if payload.get("missing_evidence"):
            reasons.append("missing_evidence")
        if payload.get("conflicting_evidence"):
            reasons.append("conflicting_evidence")
        if payload.get("security_alert"):
            reasons.append("security_alert")
        if payload.get("budget_breach"):
            reasons.append("budget_breach")
        if payload.get("sentiment_risk"):
            reasons.append("sentiment_risk")
        return reasons

    def _dispatch_to_agent(self, task: TaskRecord, event: EventRecord) -> dict[str, Any]:
        agent = self.ctx.agents.get(task.assigned_to)
        if agent is None:
            result = {
                "agent_id": "AIo",
                "status": "no_agent",
                "uncertainty": "high",
                "evidence": event.evidence_refs,
            }
        else:
            agent_input = {
                "task_id": task.task_id,
                "trace_id": task.trace_id,
                "event_type": event.event_type,
                "payload": event.payload,
                "evidence_refs": [ref.model_dump() for ref in event.evidence_refs],
            }
            result = agent.run(agent_input)
        self._audit(
            trace_id=task.trace_id,
            actor_id=task.assigned_to,
            actor_type=ActorType.AGENT,
            level=task.permission_level,
            action="agent_dispatched",
            status="completed",
            inputs={"task_id": task.task_id},
            outputs=result,
            evidence_refs=event.evidence_refs,
        )
        return result

    async def _execute_agent_plan(self, task: TaskRecord, event: EventRecord, agent_result: dict[str, Any]) -> None:
        tool_name = agent_result.get("recommended_tool")
        if not tool_name:
            self.ctx.storage.update_task_status(task.task_id, "completed", {"agent_result": agent_result})
            self.ctx.storage.update_event_status(event.event_id, "completed")
            return
        spec = self.ctx.tool_registry.get(tool_name)
        agent = self.ctx.agents.get(task.assigned_to)
        allowed_tools = agent.allowed_tools if agent else set()
        if tool_name not in allowed_tools:
            self.ctx.storage.update_task_status(task.task_id, "blocked", {"reason": "tool_not_allowed"})
            self.ctx.storage.update_event_status(event.event_id, "blocked")
            self._audit(
                trace_id=task.trace_id,
                actor_id="AIo",
                actor_type=ActorType.ORCHESTRATOR,
                level=PermissionLevel.L4_HIGH_RISK,
                action="tool_blocked",
                status="blocked",
                inputs={"tool": tool_name},
                outputs={"reason": "tool_not_allowed"},
                evidence_refs=event.evidence_refs,
            )
            return

        action_context = self._build_action_context(task, event, spec)
        decision = self.ctx.policy_engine.evaluate(action_context)
        self._audit(
            trace_id=task.trace_id,
            actor_id="AIo",
            actor_type=ActorType.ORCHESTRATOR,
            level=spec.permission_level,
            action="policy_evaluated",
            status="requires_approval" if decision.requires_approval else "completed",
            inputs=action_context,
            outputs=decision.model_dump(mode="json"),
            evidence_refs=event.evidence_refs,
            policy_decision=decision,
        )

        if decision.requires_approval:
            approval = ApprovalRequest(
                trace_id=task.trace_id,
                requested_action={
                    "tool_name": spec.name,
                    "payload_hash": hash_payload(action_context),
                    "payload_ref": f"event://{event.event_id}",
                },
                risk_level=PermissionLevel.L4_HIGH_RISK,
                required_asl=decision.required_asl or action_context.get("required_asl"),
                evidence_refs=event.evidence_refs,
                reason=";".join(decision.reasons),
            )
            self.ctx.storage.create_approval(approval)
            self.ctx.storage.update_task_status(task.task_id, "awaiting_approval", {"approval_id": approval.approval_id})
            self.ctx.storage.update_event_status(event.event_id, "awaiting_approval")
            return

        tool_payload = self._build_tool_payload(task, event, agent_result, spec)
        result = self.ctx.tool_registry.execute(
            name=spec.name,
            payload=tool_payload,
            trace_id=task.trace_id,
            actor_id=task.assigned_to,
            policy_decision=decision,
            audit_callback=self.ctx.storage.add_audit,
        )
        if result.get("post_check_failed"):
            self.ctx.storage.update_task_status(
                task.task_id,
                "rolled_back",
                {"reason": result.get("post_check_failed"), "result": result},
            )
            self.ctx.storage.update_event_status(event.event_id, "rolled_back")
        else:
            self.ctx.policy_engine.record_success(action_context)
            self.ctx.storage.update_task_status(task.task_id, "completed", {"result": result})
            self.ctx.storage.update_event_status(event.event_id, "completed")
            self.ctx.storage.store_memory(
                MemoryRecord(
                    trace_id=task.trace_id,
                    scope="long_term",
                    key=f"lesson:{event.event_type}",
                    value={"tool": spec.name, "result_hash": hash_payload(result)},
                )
            )

    def _build_action_context(self, task: TaskRecord, event: EventRecord, spec: Any) -> dict[str, Any]:
        now = datetime.now(timezone.utc)
        payload = event.payload
        recipient_domain = payload.get("recipient_domain")
        recipient = payload.get("recipient", "internal@example.com")
        if not recipient_domain:
            recipient_domain = recipient.split("@")[-1] if isinstance(recipient, str) and "@" in recipient else "internal.local"
        return {
            "trace_id": task.trace_id,
            "task_id": task.task_id,
            "tool_name": spec.name,
            "permission_level": spec.permission_level.value,
            "external_impact": spec.external_impact,
            "amount": payload.get("amount"),
            "recipient_domain": recipient_domain,
            "content_hash": hash_payload(payload.get("message", payload)),
            "workflow": event.event_type,
            "invoked_hour_utc": now.hour,
            "complaint_signals": payload.get("complaint_signals", []),
            "conflicting_evidence": payload.get("conflicting_evidence", False),
            "missing_evidence": payload.get("missing_evidence", False),
            "required_asl": payload.get("required_asl"),
        }

    def _build_tool_payload(
        self, task: TaskRecord, event: EventRecord, agent_result: dict[str, Any], spec: Any
    ) -> dict[str, Any]:
        payload = dict(event.payload)
        payload.setdefault("trace_id", task.trace_id)
        payload.setdefault("task_id", task.task_id)
        payload.setdefault("agent_id", task.assigned_to)
        payload.setdefault("tool_name", spec.name)
        payload.setdefault("body_ref", agent_result.get("draft_response", {}).get("draft_ref", "doc://draft"))
        payload.setdefault("details_ref", "doc://details")
        payload.setdefault("correction_ref", "doc://correction")
        return payload

    def _audit(
        self,
        trace_id: str,
        actor_id: str,
        actor_type: ActorType,
        level: PermissionLevel,
        action: str,
        status: str,
        inputs: dict[str, Any],
        outputs: dict[str, Any],
        evidence_refs: list[Any],
        policy_decision: Any | None = None,
    ) -> None:
        record = AuditRecord(
            trace_id=trace_id,
            actor_id=actor_id,
            actor_type=actor_type,
            permission_level=level,
            action=action,
            status=status,
            inputs=inputs,
            outputs=outputs,
            evidence_refs=evidence_refs,
            policy_decision=policy_decision,
        )
        self.ctx.storage.add_audit(record)
