import type { PersonalityProfile } from "./personality-types.js";

export const SAMPLE_PERSONALITY_PROFILES: PersonalityProfile[] = [
  {
    id: "aoi-builder",
    name: "Aoi Rin",
    simulationLabel: "Open-rule builder companion",
    role: "Crystal Builder",
    character: {
      archetype: "Practical atelier heroine",
      visualTheme: "rose work dress, tool sash, warm brown twin-tail hair",
      hairColor: [0.24, 0.13, 0.09],
      skinColor: [0.96, 0.76, 0.62],
      outfitColor: [0.92, 0.36, 0.48],
      accentColor: [0.98, 0.78, 0.34],
      eyeColor: [0.22, 0.58, 0.88],
    },
    values: { stability: 0.72, creativity: 0.74, community: 0.64, efficiency: 0.7, autonomy: 0.58 },
    priorities: { foodSecurity: 0.55, construction: 0.86, research: 0.48, socialCare: 0.42, exploration: 0.38 },
    workStyle: "steady",
    socialTendency: 0.52,
    riskTolerance: 0.42,
    obedienceIndependence: 0.46,
    routinePreference: 0.68,
    communicationStyle: "Concise rationale with practical next steps",
    redLines: ["hidden identity claims", "harmful commands", "wasteful resource use"],
    roleAffinity: { builder: 0.94, gatherer: 0.5, planner: 0.58, caretaker: 0.38, hauler: 0.62 },
  },
  {
    id: "mira-planner",
    name: "Mira Kisaragi",
    simulationLabel: "Risk-visible civic companion",
    role: "Civic Planner",
    character: {
      archetype: "Calm strategist heroine",
      visualTheme: "navy capelet, pale blue skirt, short silver hair",
      hairColor: [0.72, 0.78, 0.86],
      skinColor: [0.95, 0.74, 0.61],
      outfitColor: [0.24, 0.38, 0.72],
      accentColor: [0.64, 0.84, 1],
      eyeColor: [0.46, 0.88, 0.94],
    },
    values: { stability: 0.9, creativity: 0.36, community: 0.74, efficiency: 0.64, autonomy: 0.32 },
    priorities: { foodSecurity: 0.82, construction: 0.45, research: 0.66, socialCare: 0.62, exploration: 0.14 },
    workStyle: "analytical",
    socialTendency: 0.58,
    riskTolerance: 0.18,
    obedienceIndependence: 0.28,
    routinePreference: 0.82,
    communicationStyle: "Warns early and explains risk tradeoffs",
    redLines: ["dangerous expansion", "ignoring shortages"],
    roleAffinity: { builder: 0.42, gatherer: 0.58, planner: 0.92, caretaker: 0.68, hauler: 0.46 },
  },
  {
    id: "sena-scout",
    name: "Sena Vale",
    simulationLabel: "Autonomy-visible scout companion",
    role: "Aether Scout",
    character: {
      archetype: "Energetic explorer heroine",
      visualTheme: "mint travel jacket, shorts over leggings, auburn side-tail hair",
      hairColor: [0.55, 0.25, 0.12],
      skinColor: [0.93, 0.7, 0.55],
      outfitColor: [0.22, 0.66, 0.52],
      accentColor: [0.98, 0.62, 0.28],
      eyeColor: [0.32, 0.86, 0.54],
    },
    values: { stability: 0.34, creativity: 0.7, community: 0.44, efficiency: 0.54, autonomy: 0.88 },
    priorities: { foodSecurity: 0.44, construction: 0.35, research: 0.46, socialCare: 0.24, exploration: 0.92 },
    workStyle: "adaptive",
    socialTendency: 0.34,
    riskTolerance: 0.78,
    obedienceIndependence: 0.86,
    routinePreference: 0.22,
    communicationStyle: "Short updates, prefers action over discussion",
    redLines: ["strict routine locks", "commands without purpose"],
    roleAffinity: { builder: 0.36, gatherer: 0.78, planner: 0.28, caretaker: 0.24, hauler: 0.42 },
  },
  {
    id: "hana-caretaker",
    name: "Hana Sol",
    simulationLabel: "Care-visible support companion",
    role: "Hearth Caretaker",
    character: {
      archetype: "Gentle support heroine",
      visualTheme: "cream apron dress, green ribbon, soft pink bob hair",
      hairColor: [0.92, 0.52, 0.64],
      skinColor: [0.97, 0.78, 0.64],
      outfitColor: [0.72, 0.86, 0.58],
      accentColor: [1, 0.86, 0.72],
      eyeColor: [0.56, 0.74, 0.42],
    },
    values: { stability: 0.68, creativity: 0.44, community: 0.92, efficiency: 0.42, autonomy: 0.36 },
    priorities: { foodSecurity: 0.72, construction: 0.32, research: 0.3, socialCare: 0.94, exploration: 0.18 },
    workStyle: "supportive",
    socialTendency: 0.9,
    riskTolerance: 0.26,
    obedienceIndependence: 0.34,
    routinePreference: 0.58,
    communicationStyle: "Warm summaries focused on morale and needs",
    redLines: ["neglecting exhausted agents", "social isolation mandates"],
    roleAffinity: { builder: 0.32, gatherer: 0.55, planner: 0.48, caretaker: 0.95, hauler: 0.54 },
  },
  {
    id: "koharu-operator",
    name: "Koharu Finch",
    simulationLabel: "Throughput-visible logistics companion",
    role: "Logistics Operator",
    character: {
      archetype: "Sharp logistics heroine",
      visualTheme: "amber utility coat, black leggings, dark teal ponytail hair",
      hairColor: [0.05, 0.24, 0.28],
      skinColor: [0.94, 0.72, 0.58],
      outfitColor: [0.92, 0.62, 0.18],
      accentColor: [0.18, 0.82, 0.88],
      eyeColor: [0.98, 0.9, 0.34],
    },
    values: { stability: 0.58, creativity: 0.38, community: 0.4, efficiency: 0.94, autonomy: 0.46 },
    priorities: { foodSecurity: 0.58, construction: 0.68, research: 0.42, socialCare: 0.22, exploration: 0.28 },
    workStyle: "burst",
    socialTendency: 0.28,
    riskTolerance: 0.52,
    obedienceIndependence: 0.38,
    routinePreference: 0.5,
    communicationStyle: "Direct status reports with metrics",
    redLines: ["idle cycles during shortages", "unclear priorities"],
    roleAffinity: { builder: 0.62, gatherer: 0.62, planner: 0.44, caretaker: 0.2, hauler: 0.9 },
  },
];
