export const CONFIG = {
  identity: {
    title: "Skyshard Surge",
    subtitle: "Original voxel action prototype",
  },
  debug: {
    fixedStep: 1 / 60,
  },
  world: {
    seed: 90210,
    chunkSize: 16,
    height: 48,
    loadRadius: 2,
    unloadPadding: 1,
    maxTargetDistance: 8,
    initialSpawn: { x: 8, z: 8 },
  },
  player: {
    bodyRadius: 0.36,
    height: 1.8,
    eyeHeight: 1.55,
    walkSpeed: 8,
    sprintSpeed: 13.5,
    flightSpeed: 22,
    jumpSpeed: 9.5,
    gravity: 28,
    airControl: 0.35,
    dashSpeed: 35,
    dashDuration: 0.18,
    dashCooldown: 0.9,
    mouseSensitivity: 0.0022,
    lookClamp: 1.35,
  },
  resources: {
    maxHp: 100,
    maxStamina: 100,
    maxEnergy: 100,
    sprintDrainPerSecond: 18,
    staminaRecoveryPerSecond: 24,
    dashStaminaCost: 34,
    flightDrainPerSecond: 16,
    energyRecoveryPerSecond: 20,
    projectileEnergyCost: 18,
    voidDamage: 15,
  },
  combat: {
    projectileSpeed: 42,
    projectileLifetime: 1.5,
    projectileRadius: 2.25,
    projectileDamage: 36,
    projectileDirectHitBonus: 18,
    fireCooldown: 0.14,
    projectilePoolSize: 24,
  },
  dummy: {
    maxHp: 120,
    hitRadius: 0.9,
    respawnSeconds: 6,
  },
};
