// @ts-nocheck

export const CONFIG = {
  identity: {
    title: "Skyshard Surge",
    subtitle: "Original voxel action prototype",
  },
  debug: {
    fixedStep: 1 / 60,
  },
  world: {
    seed: 90210,
    chunkSize: 16,
    height: 48,
    loadRadius: 2,
    unloadPadding: 1,
    maxTargetDistance: 8,
    initialSpawn: { x: 8, z: 8 },
  },
  player: {
    bodyRadius: 0.36,
    height: 1.8,
    eyeHeight: 1.55,
    walkSpeed: 8,
    sprintSpeed: 13.5,
    flightSpeed: 22,
    flightSprintMultiplier: 1.18,
    flightAcceleration: 10,
    jumpSpeed: 9.5,
    gravity: 28,
    fallGravityMultiplier: 1.22,
    jumpCutGravityMultiplier: 1.9,
    maxFallSpeed: 26,
    groundAcceleration: 18,
    groundDeceleration: 16,
    airAcceleration: 5.5,
    airDeceleration: 3.2,
    coyoteTime: 0.12,
    jumpBufferTime: 0.14,
    dashSpeed: 35,
    dashDuration: 0.2,
    dashCooldown: 0.78,
    mouseSensitivity: 0.0022,
    lookClamp: 1.35,
    baseFov: 0.95,
    maxFov: 1.2,
    speedFovScale: 0.0036,
    dashFovBoost: 0.075,
    flightFovBoost: 0.028,
    fovSmoothing: 0.16,
  },
  resources: {
    maxHp: 100,
    maxStamina: 100,
    maxEnergy: 100,
    respawnHp: 65,
    sprintDrainPerSecond: 18,
    staminaRecoveryPerSecond: 24,
    dashStaminaCost: 34,
    flightDrainPerSecond: 16,
    energyRecoveryPerSecond: 20,
    projectileEnergyCost: 18,
    voidDamage: 15,
    damageInvulnerabilityTime: 0.55,
  },
  combat: {
    projectileSpeed: 42,
    projectileLifetime: 1.5,
    projectileRadius: 2.25,
    projectileDamage: 36,
    projectileDirectHitBonus: 18,
    fireCooldown: 0.14,
    projectilePoolSize: 24,
  },
  dummy: {
    maxHp: 120,
    hitRadius: 0.9,
    respawnSeconds: 6,
  },
  enemy: {
    skimmerMaxHp: 72,
    skimmerHitRadius: 0.72,
    hoverHeight: 1.9,
    hoverAmplitude: 0.22,
    moveSpeed: 4.8,
    accel: 4.5,
    aggroRange: 18,
    leashRange: 26,
    contactRange: 1.5,
    contactDamage: 12,
    contactImpulse: 8.5,
    contactCooldown: 1.15,
    respawnSeconds: 5.5,
    roster: [
      { kind: "dummy", x: 16, z: 14 },
      { kind: "skimmer", x: 23, z: 10 },
      { kind: "skimmer", x: 10, z: 24 },
      { kind: "skimmer", x: 27, z: 22 },
    ],
  },
};
